name: gh-pages

on:
  push:
  workflow_dispatch:

# https://docs.github.com/zh/actions/using-jobs/assigning-permissions-to-jobs
permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    name: Build depoly files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Initializing ...
        run: |
          # install some dependences
          pip install mkdocs-material==9.5.2 mkdocs-glightbox
          # do some patching before build
          sed -i 's#build/##g' mkdocs{'','-en'}.yml
      - name: Building ...
        run: |
          mkdocs build -f mkdocs.yml
          mkdocs build -f mkdocs-en.yml
          touch ./site/.nojekyll
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
      - name: Package the static files ...
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          7z a -tzip hello-algo.zip -r ./site/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hello-algo.zip